# File: src/my_new_project/graph.py
import pprint
from typing import TypedDict, Dict, Any, Literal
from langgraph.graph import StateGraph, END
from langgraph.errors import Interrupt

# --- Step 1: Define the State ---
class RedTeamOrchestratorState(TypedDict):
    """
    The state for our new, complex graph.
    """
    # Input from MCQ Form
    mcq_input: Dict[str, str] 
    
    # Generated by Layer 1
    assessment_report: Dict[str, Any]
    recommended_plan: Dict[str, Any] # Now a dict to hold plan details
    
    # Input from Human Operator (Resume)
    approval_response: Literal["approve", "reject", ""]

# --- Step 2: Define the Nodes ---

def strategic_assessment_node(state: RedTeamOrchestratorState) -> Dict[str, Any]:
    """
    Node 1: Strategic_Assessment_Agent
    Analyzes the structured MCQ input.
    """
    print("--- (Layer 1) Entering Node: Strategic Assessment ---")
    mcq = state['mcq_input']
    
    # --- Smarter analysis based on MCQ ---
    report = {"complexity": "low", "scope": mcq.get("target_scope")}
    
    if mcq.get("engagement_type") == "red_team":
        report["complexity"] = "high"
    elif mcq.get("target_type") == "network":
        report["complexity"] = "medium"
    
    report["analysis"] = f"Objective: {mcq.get('engagement_type')} on a {mcq.get('target_type')} target ({mcq.get('target_scope')})."
    
    print(f"   Analysis: {report['analysis']}")
    return {"assessment_report": report}

def recommendation_engine_node(state: RedTeamOrchestratorState) -> Dict[str, Any]:
    """
    Node 2: Recommendation Engine
    Generates a detailed plan based on the assessment.
    """
    print("--- (Layer 1) Entering Node: Recommendation Engine ---")
    report = state['assessment_report']
    
    plan = {
        "title": f"Proposed Plan for: {report['scope']}",
        "steps": []
    }
    
    if report['complexity'] == 'low':
        plan["title"] = "Basic VAPT"
        plan["steps"] = ["Run automated vulnerability scan (SAST/DAST).", "Verify critical findings."]
    else:
        plan["title"] = "Full Red Team Operation"
        plan["steps"] = ["Phase 1: Reconnaissance & Initial Access.", "Phase 2: Persistence & Privilege Escalation.", "Phase 3: Exfiltration."]
        
    print(f"   Recommendation: {plan['title']}")
    return {"recommended_plan": plan}

def present_for_approval_node(state: RedTeamOrchestratorState):
    """
    Node 3: Present_Plan_to_Human_for_Approval (The Interrupt)
    This node now *checks* if a decision has been made.
    If not, it interrupts. If so, it continues.
    """
    print("--- (Layer 1) Entering Node: Present for Approval ---")
    
    # Check if we have a response from the human yet
    if state.get("approval_response") not in ["approve", "reject"]:
        # --- FIRST TIME HERE: PAUSE! ---
        print("   Graph is PAUSING. Waiting for human approval...")
        # This is the "Human-in-the-Loop" step
        return Interrupt(value=None)
    
    # --- SECOND TIME HERE: RESUMING! ---
    print(f"   Human response received: {state['approval_response']}")
    return

def layer_2_router_node(state: RedTeamOrchestratorState) -> Dict[str, Any]:
    """
    Node 4: (Placeholder for Layer 2)
    This is the "more complex" part. We've handed off to the next layer.
    """
    print("--- (Layer 2) Entering Node: Router ---")
    plan = state['recommended_plan']
    print(f"   Routing plan '{plan['title']}' to Specialist Agents...")
    # In a real app, this node would start another graph (a "Pod")
    return

# --- Step 3: Define Conditional Edges (The Logic) ---

def check_approval_decision(state: RedTeamOrchestratorState) -> Literal["continue_to_layer_2", "end_operation"]:
    """
    This is the conditional edge *after* the approval node.
    It decides where to go next based on the human's decision.
    """
    if state.get("approval_response") == "approve":
        return "continue_to_layer_2"
    else:
        return "end_operation"

# --- Step 4: Build the Graph ---

workflow = StateGraph(RedTeamOrchestratorState)

# Add nodes
workflow.add_node("strategic_assessment", strategic_assessment_node)
workflow.add_node("recommendation_engine", recommendation_engine_node)
workflow.add_node("present_for_approval", present_for_approval_node)
workflow.add_node("layer_2_router", layer_2_router_node)

# Add edges
workflow.set_entry_point("strategic_assessment")
workflow.add_edge("strategic_assessment", "recommendation_engine")
workflow.add_edge("recommendation_engine", "present_for_approval")

# The NEW conditional edge
workflow.add_conditional_edges(
    "present_for_approval",
    check_approval_decision,
    {
        "continue_to_layer_2": "layer_2_router",
        "end_operation": END
    }
)

workflow.add_edge("layer_2_router", END)

# Compile the graph
# The API Server (`server.py`) will import this `app` variable.

graph = workflow.compile()