import json
import os
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

import requests
from fastapi import FastAPI, HTTPException, Query, Request
from fastapi.responses import FileResponse

app = FastAPI(title="ACIP SOC API", version="1.1.0")

# Configurable DevSecOps endpoint for SOC alert forwarding.
DEVSECOPS_ENDPOINT = os.getenv(
    "DEVSECOPS_SOC_ALERT_ENDPOINT",
    "http://127.0.0.1:8000/api/v1/soc/alerts",
)
SOC_REPORT_PATH = Path(__file__).resolve().parent / "soc_final_report.json"
OUTPUTS_DIR = Path(__file__).resolve().parent / "outputs"
UI_DIR = Path(__file__).resolve().parent / "ui" / "web"
MAX_ALERT_HISTORY = 500

soc_alert_history: List[Dict[str, Any]] = []
hitl_decisions: Dict[str, Dict[str, Any]] = {}


def _categorize(score: float) -> str:
    if score >= 9.0:
        return "CRITICAL"
    if score >= 7.0:
        return "HIGH"
    if score >= 4.0:
        return "MEDIUM"
    if score > 0.0:
        return "LOW"
    return "NONE"


def _safe_float(value: Any, default: float = 0.0) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return default


def _normalize_alert(incoming: Dict[str, Any]) -> Dict[str, Any]:
    severity_value = _safe_float(incoming.get("severity", 0.0))
    payload = incoming.get("data payload")
    if not isinstance(payload, dict):
        payload = incoming.get("data_payload")
    if not isinstance(payload, dict):
        payload = {}

    alert_id = (
        incoming.get("alert_id")
        or incoming.get("id")
        or incoming.get("file_name")
        or f"soc-alert-{uuid.uuid4().hex[:6]}"
    )

    raw_data = incoming.get("raw_data")
    if not isinstance(raw_data, dict):
        raw_data = {
            "standard_output": incoming,
            "payload": payload,
        }

    router_name = incoming.get("router name") or incoming.get("router_name")
    pod_name = incoming.get("pod name") or incoming.get("pod_name")
    source_ip = payload.get("src_ip") or payload.get("source_ip") or incoming.get("source_ip")
    affected_target = (
        incoming.get("affected_target")
        or payload.get("target_ip")
        or payload.get("target ip")
        or payload.get("affected_target")
        or source_ip
        or "192.168.56.104"
    )
    alert_type = (
        incoming.get("alert_type")
        or incoming.get("attack_type")
        or incoming.get("scenario")
        or router_name
        or pod_name
        or "soc_event"
    )
    description = (
        incoming.get("description")
        or incoming.get("ai thought process")
        or incoming.get("ai_thought_process")
        or payload.get("description")
        or "SOC workflow output generated by ACIP"
    )

    normalized = {
        "alert_id": alert_id,
        "alert_type": alert_type,
        "severity": severity_value,
        "title": incoming.get("title") or str(alert_type).replace("_", " ").title(),
        "description": description,
        "source_module": incoming.get("source_module") or incoming.get("module name") or "soc",
        "router_name": router_name,
        "pod_name": pod_name,
        "status": incoming.get("status", "unknown"),
        "affected_target": affected_target,
        "code_snippet": incoming.get("code_snippet"),
        "file_path": incoming.get("file_path") or incoming.get("file_name"),
        "network_details": incoming.get("network_details"),
        "raw_data": raw_data,
        "timestamp": incoming.get("timestamp")
        or datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
    }
    normalized["risk_level"] = _categorize(severity_value)
    return normalized


def _save_latest_report(alert: Dict[str, Any]) -> None:
    with SOC_REPORT_PATH.open("w", encoding="utf-8") as report_file:
        json.dump(alert, report_file, indent=4, ensure_ascii=False)


def _remember_alert(alert: Dict[str, Any]) -> None:
    alert_id = str(alert.get("alert_id", ""))
    if alert_id in hitl_decisions:
        alert.update(hitl_decisions[alert_id])

    existing_index: Optional[int] = None
    for idx, item in enumerate(soc_alert_history):
        if item.get("alert_id") == alert.get("alert_id"):
            existing_index = idx
            break

    if existing_index is not None:
        soc_alert_history.pop(existing_index)

    soc_alert_history.append(alert)

    if len(soc_alert_history) > MAX_ALERT_HISTORY:
        del soc_alert_history[:-MAX_ALERT_HISTORY]


def _update_alert_status(alert_id: str, status: str, decision: str) -> Dict[str, Any]:
    allowed_statuses = {
        "approved_mitigated",
        "investigating",
        "dismissed",
    }
    if status not in allowed_statuses:
        raise HTTPException(status_code=400, detail=f"Unsupported HITL status: {status}")

    _sync_output_data()
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    decision_payload = {
        "status": status,
        "hitl_decision": decision,
        "hitl_updated_at": now,
    }
    hitl_decisions[alert_id] = decision_payload

    for alert in reversed(soc_alert_history):
        if alert.get("alert_id") == alert_id:
            alert.update(decision_payload)
            _save_latest_report(alert)
            return alert

    raise HTTPException(status_code=404, detail=f"SOC alert {alert_id} not found")


def _forward_to_devsecops(alert: Dict[str, Any]) -> Dict[str, Any]:
    try:
        response = requests.post(DEVSECOPS_ENDPOINT, json=alert, timeout=5)
        response.raise_for_status()
        return {
            "forwarded": True,
            "endpoint": DEVSECOPS_ENDPOINT,
            "status_code": response.status_code,
        }
    except requests.RequestException as exc:
        return {
            "forwarded": False,
            "endpoint": DEVSECOPS_ENDPOINT,
            "error": str(exc),
        }


def _process_incoming_alert(incoming: Dict[str, Any]) -> Dict[str, Any]:
    final_json_output = _normalize_alert(incoming)

    print("\n" + "=" * 60)
    print("[SOC ANALYST] NEW STRUCTURED JSON GENERATED:")
    print("=" * 60)
    print(json.dumps(final_json_output, indent=4, ensure_ascii=False))
    print("=" * 60 + "\n")

    _save_latest_report(final_json_output)
    _remember_alert(final_json_output)
    forward_result = _forward_to_devsecops(final_json_output)

    return {**final_json_output, "forwarding": forward_result}


def _load_bootstrap_data() -> None:
    sources: List[Path] = []
    if OUTPUTS_DIR.exists():
        sources.extend(
            sorted(
                OUTPUTS_DIR.glob("*.json"),
                key=lambda item: item.stat().st_mtime,
            )
        )
    if SOC_REPORT_PATH.exists():
        sources.append(SOC_REPORT_PATH)

    for source in sources[-MAX_ALERT_HISTORY:]:
        try:
            payload = json.loads(source.read_text(encoding="utf-8"))
            if isinstance(payload, dict):
                payload["file_name"] = source.name
                alert = _normalize_alert(payload)
                if alert.get("severity", 0.0) == 0.0:
                    alert["severity"] = _infer_severity(payload)
                    alert["risk_level"] = _categorize(alert["severity"])
                _remember_alert(alert)
        except Exception:
            # Non-fatal bootstrap read error; service still starts.
            continue


def _infer_severity(payload: Dict[str, Any]) -> float:
    text = json.dumps(payload, ensure_ascii=False).lower()
    if "critical" in text:
        return 9.2
    if "high" in text or "anomaly" in text or "failed ssh" in text:
        return 7.4
    if "medium" in text or "triage" in text:
        return 5.5
    if "low" in text:
        return 2.5
    return 3.0


def _sync_output_data() -> None:
    _load_bootstrap_data()


_load_bootstrap_data()


@app.get("/", tags=["Health"])
def read_root() -> Dict[str, Any]:
    _sync_output_data()
    return {
        "service_status": "Running",
        "module_name": "soc_defense",
        "version": "1.1.0",
        "dashboard_url": "/dashboard",
        "alerts_count": len(soc_alert_history),
    }


@app.post("/api/v1/soc/ingest", tags=["SOC"])
async def ingest_raw_data(request: Request):
    try:
        incoming = await request.json()
        if not isinstance(incoming, dict):
            raise HTTPException(status_code=400, detail="JSON body must be an object")
        return _process_incoming_alert(incoming)
    except HTTPException:
        raise
    except Exception as exc:
        print(f"Error: {str(exc)}")
        raise HTTPException(status_code=500, detail=str(exc)) from exc


@app.post("/api/v1/soc/alerts", tags=["SOC"])
async def create_structured_alert(request: Request):
    try:
        incoming = await request.json()
        if not isinstance(incoming, dict):
            raise HTTPException(status_code=400, detail="JSON body must be an object")
        return _process_incoming_alert(incoming)
    except HTTPException:
        raise
    except Exception as exc:
        print(f"Error: {str(exc)}")
        raise HTTPException(status_code=500, detail=str(exc)) from exc


@app.get("/api/v1/soc/latest-report", tags=["SOC"])
async def get_latest_report():
    if not SOC_REPORT_PATH.exists():
        return {"message": "No reports available"}
    try:
        return json.loads(SOC_REPORT_PATH.read_text(encoding="utf-8"))
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Failed to load latest SOC report: {exc}") from exc


@app.get("/api/v1/soc/alerts", tags=["SOC"])
def list_soc_alerts(limit: int = Query(default=50, ge=1, le=500)) -> Dict[str, Any]:
    _sync_output_data()
    items = list(reversed(soc_alert_history))[:limit]
    return {
        "total": len(soc_alert_history),
        "count": len(items),
        "items": items,
    }


@app.get("/api/v1/soc/alerts/{alert_id}", tags=["SOC"])
def get_soc_alert(alert_id: str) -> Dict[str, Any]:
    _sync_output_data()
    for alert in reversed(soc_alert_history):
        if alert.get("alert_id") == alert_id:
            return alert
    raise HTTPException(status_code=404, detail=f"SOC alert {alert_id} not found")


@app.patch("/api/v1/soc/alerts/{alert_id}/status", tags=["SOC"])
async def update_soc_alert_status(alert_id: str, request: Request) -> Dict[str, Any]:
    try:
        incoming = await request.json()
        if not isinstance(incoming, dict):
            raise HTTPException(status_code=400, detail="JSON body must be an object")

        status = str(incoming.get("status", "")).strip().lower()
        decision = str(incoming.get("decision") or status).strip()
        return _update_alert_status(alert_id, status, decision)
    except HTTPException:
        raise
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc


@app.get("/api/v1/soc/dashboard/summary", tags=["Dashboard"])
def dashboard_summary() -> Dict[str, Any]:
    _sync_output_data()
    risk_distribution = {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0, "NONE": 0}
    type_distribution: Dict[str, int] = {}
    router_distribution: Dict[str, int] = {}
    status_distribution: Dict[str, int] = {}

    for alert in soc_alert_history:
        risk_level = alert.get("risk_level", "NONE")
        if risk_level not in risk_distribution:
            risk_level = "NONE"
        risk_distribution[risk_level] += 1

        alert_type = str(alert.get("alert_type", "unknown"))
        type_distribution[alert_type] = type_distribution.get(alert_type, 0) + 1
        router_name = str(alert.get("router_name") or "direct_ingest")
        router_distribution[router_name] = router_distribution.get(router_name, 0) + 1
        status = str(alert.get("status") or "unknown")
        status_distribution[status] = status_distribution.get(status, 0) + 1

    return {
        "summary": {
            "total_alerts": len(soc_alert_history),
            "critical_alerts": risk_distribution["CRITICAL"],
            "high_alerts": risk_distribution["HIGH"],
            "successful_outputs": status_distribution.get("success", 0),
            "latest_alert_id": soc_alert_history[-1]["alert_id"] if soc_alert_history else None,
            "latest_timestamp": soc_alert_history[-1]["timestamp"] if soc_alert_history else None,
        },
        "risk_distribution": risk_distribution,
        "type_distribution": type_distribution,
        "router_distribution": router_distribution,
        "status_distribution": status_distribution,
    }


@app.get("/dashboard", tags=["Dashboard"])
def serve_dashboard() -> FileResponse:
    dashboard_file = UI_DIR / "dashboard.html"
    if not dashboard_file.exists():
        raise HTTPException(status_code=404, detail="Dashboard UI not found")
    return FileResponse(dashboard_file)


@app.get("/dashboard/assets/{asset_name}", tags=["Dashboard"])
def serve_dashboard_asset(asset_name: str) -> FileResponse:
    safe_name = Path(asset_name).name
    file_path = UI_DIR / safe_name
    if not file_path.exists() or not file_path.is_file():
        raise HTTPException(status_code=404, detail=f"Asset {safe_name} not found")
    return FileResponse(file_path)


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="127.0.0.1", port=8080)
